services:
  postgresql:
    image: postgres:14.18
    container_name: postgresql
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - korea-policy-news-net

volumes:
  postgres-data:
    driver: local
    name: dw-postgres-data-volume
