services:
  elasticsearch:
    image: elasticsearch:8.18.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # 보안 기능 비활성화 - 개발 편의성
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m' # 메모리 사용량 제한
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - korea-policy-news-net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  logstash:
    image: logstash:8.18.3
    container_name: logstash
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./jdbc-driver:/usr/share/logstash/jdbc-driver:ro # JDBC 드라이버를 위한 볼륨
    environment:
      - 'LS_JAVA_OPTS=-Xms256m -Xmx256m' # 메모리 사용량 제한
    networks:
      - korea-policy-news-net
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.18.3
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # Kibana가 연결할 ES 주소
    networks:
      - korea-policy-news-net
    depends_on:
      - elasticsearch

volumes:
  es-data:
    driver: local
    name: dm-es-data-volume
