services:
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=myuser
      - MINIO_ROOT_PASSWORD=mypassword
    volumes:
      - minio-data:/data
    networks:
      - korea-policy-news-net

volumes:
  minio-data:
    driver: local
    name: dl-minio-data-volume
